---

- name: Cisco Meraki
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - include_vars: main.yml

  - name: Query Cisco Meraki devices
    meraki_device:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      state: query
    register: _devices

  - name: Debug devices
    debug: 
      var: _devices

  # - name: Add Cisco Meraki device into a network
  #   meraki_device:
  #     host: "{{ meraki_host }}"
  #     validate_certs: "{{ validate_certs }}"
  #     auth_key: "{{ auth_key }}"
  #     org_name: "{{ org_name }}"
  #     net_name: "{{ net_name }}"
  #     serial: "{{ device_serial }}"
  #     state: present

  - name: Query Cisco Meraki wireless (MR) SSID
    meraki_mr_ssid:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      serial: "{{ device_serial }}"
      state: query

  - name: Change and activate Cisco Meraki wireless (MR) SSID
    meraki_mr_ssid:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      serial: "{{ device_serial }}"
      name: "{{ wireless_ssid }}"
      enabled: true
      state: present
    delegate_to: localhost




  # - name: Query Cisco Meraki Firewall services
  #   meraki_firewalled_services:
  #     host: "{{ meraki_host }}"
  #     validate_certs: "{{ validate_certs }}"
  #     auth_key: "{{ auth_key }}"
  #     org_name: "{{ org_name }}"
  #     net_name: "{{ net_name }}"
  #     state: query
  #     service: ICMP
  #   delegate_to: localhost


  # - name: Debug Meraki
  #   debug:
  #     var: _?
