---

- name: Cisco Meraki
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - include_vars: main.yml

# DEVICES
  - name: Query Cisco Meraki devices
    meraki_device:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      state: query
    register: _devices

  - name: Debug devices
    debug: 
      var: _devices

  - name: Add Cisco Meraki device into a network
    meraki_device:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      serial: "{{ device_serial }}"
      state: present

# FIREWALL
  # services
  - name: Allow Cisco Meraki Firewall ICMP services
    meraki_firewalled_services:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      state: present
      access: restricted
      service: ICMP
      allowed_ips:
        - 192.0.1.1
        - 192.0.1.2

  - name: Query Cisco Meraki Firewall services
    meraki_firewalled_services:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      state: query

  # rules
  - name: Query Cisco Meraki Firewall MR rule
    meraki_mr_l3_firewall:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      number: 1
      state: query

  - name: Allow Cisco Meraki Firewall MR rule
    meraki_mr_l3_firewall:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      state: present
      number: 1
      rules:
        - comment: test rule
          policy: allow
          protocol: tcp
          dest_port: 80
          dest_cidr: 192.168.1.0/24

  - name: Query Cisco Meraki Firewall MX rule
    meraki_mx_l3_firewall:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      state: query

  - name: Allow Cisco Meraki Firewall MX rule
    meraki_mx_l3_firewall:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      state: present
      rules:
        - comment: test rule
          policy: allow
          protocol: tcp
          dest_port: 80
          dest_cidr: 192.168.2.0/24

  # - name: Query Cisco Meraki wireless (MR) SSID
  #   meraki_mr_ssid:
  #     host: "{{ meraki_host }}"
  #     validate_certs: "{{ validate_certs }}"
  #     auth_key: "{{ auth_key }}"
  #     org_name: "{{ org_name }}"
  #     net_name: "{{ net_name }}"
  #     serial: "{{ device_serial }}"
  #     state: query
  #   register: _ssid

  # - name: Debug SSID
  #   debug: 
  #     var: _ssid

  # - name: Change and activate Cisco Meraki wireless (MR) SSID
  #   meraki_mr_ssid:
  #     host: "{{ meraki_host }}"
  #     validate_certs: "{{ validate_certs }}"
  #     auth_key: "{{ auth_key }}"
  #     org_name: "{{ org_name }}"
  #     net_name: "{{ net_name }}"
  #     serial: "{{ device_serial }}"
  #     name: "{{ wireless_ssid }}"
  #     enabled: true
  #     state: present
  #   delegate_to: localhost

