---

- name: Cisco Meraki
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - include_vars: main.yml

  - name: Query DNAC Sites
    cisco.meraki.xxx:
      dxxx

  - name: Debug Meraki
    debug:
      var: _?
