---

- name: Cisco Meraki
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
  
  - include_vars: main.yml

  - name: Query Cisco Meraki Firewall services
    meraki_firewalled_services:
      host: "{{ meraki_host }}"
      validate_certs: "{{ validate_certs }}"
      auth_key: "{{ auth_key }}"
      state: query
      org_name: "{{ org_name }}"
      net_name: "{{ net_name }}"
      service: ICMP
    delegate_to: localhost


  # - name: Debug Meraki
  #   debug:
  #     var: _?
